### ISSUE TITLE
Readme.md file's hit count link not working

### ISSUE THREAD

**Issue by slahirucd7** [scorelab/tensormap#132]
In the readme.md file, link related to the hit count included as below.
[**Hit Count**](http://hits.dwyl.com/scorelab/TensorMap)

`http://hits.dwyl.com/scorelab/TensorMap`

It's no longer available and alt text value related to the hit count is showing currently.

**Comment by piyush-palta** [comment]
@7slcode7 It is working fine now, please check.

**Comment by mesterio123** [comment]
It's working perfectly!
