### ISSUE TITLE
Problems with React -->There is no action for buttons on the website

### ISSUE THREAD

**Issue by mahmoudmohamed22** [scorelab/tensormap#170]
![Screenshot from 2022-04-17 23-36-15](https://user-images.githubusercontent.com/47304558/163815037-f0a9541f-f267-4f8f-a0f7-8bbc15dbb2c9.png)

**Comment by Kd-Here** [comment]
Thanks @mahmoudmohamed22 for pointing the issue I had resolved this by adding the missing class.
