### ISSUE TITLE
Gsoc 2019 Idea

### ISSUE THREAD

**Issue by prasadgujar** [scorelab/TensorMap#3]
Hello Everyone,

According to the Official GSOC-2019 list of project ideas of Score Lab, there is one Idea which is on Implement the TensorMap Web Application. I want to work on this Idea and want to take part in GSoC-2019. I have already introduced myself on Gitter.

**Comment by ivantha** [comment]
Please join the Gitter channel for the TensorMap here : https://gitter.im/scorelab/TensorMap
You can be considered as a candidate for the GSoC project by completing the challenge task mentioned in the channel.

**Comment by prasadgujar** [comment]
Sure, Thanks for the guidance.
