### ISSUE TITLE
Mistake in README.md

### ISSUE THREAD

**Issue by ChetanMadan** [scorelab/TensorMap#48]
In the project readme, under the setting up frontend section, the instructions should be 
```
cd TensorMap/tensormap-client 
```
instead of 
```
cd TensorMap
```
since 'yarn install' and 'npm start' do not make sense in the main directory and would return an error.

**Comment by orionpax00** [comment]
@ChetanMadan yes it should be
```bash
cd Tensormap/tensormap-client
```
