### ISSUE TITLE
Using the 'baseURL' for requests on the front-end. 

### ISSUE THREAD

**Issue by ashutosh-b-b** [scorelab/TensorMap#90]
Currently the request addresses are directly hardcoded to 'http://localhost:5000'. The hardcode should be changed to use the baseURL.

**Comment by orionpax00** [comment]
Hi @ashutosh-b-b,

baseURL is there in src/config/index.js

**Comment by ashutosh-b-b** [comment]
Yes , At some places it is not used and a direct addressing has been done.

**Comment by ashutosh-b-b** [comment]
I ll put up a PR regarding this.
